{% set name = "HipSTR2" %}
{% set version = "VERSION" %}
{% set vcommit = "VCOMMIT" %}
{% set sha = "SHA256" %}
{% set username = "USERNAME" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ username }}/{{ name }}/archive/{{ vcommit }}.tar.gz
  sha256: {{ sha }}

build:
  number: 0
  run_exports:
      - {{ pin_subpackage('hipstr2', max_pin="x.x") }}
  script:
    - mkdir -p "${PREFIX}/bin"
    - make version
    - make
    - cp HipSTR DenovoFinder "${PREFIX}/bin/"

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - htslib


test:
  commands:
    - HipSTR --help

about:
  home: https://github.com/{{ username }}/{{ name }}
  license: GPL-2
  license_file: LICENSE
  summary: Haplotype inference and phasing for Short Tandem Repeats
  description: Genotype and phase short tandem repeats using Illumina whole-genome sequencing data

extra:
  recipe-maintainers:
    - {{ username }}
  additional-platforms:
    - linux-aarch64
    - osx-arm64
