{% set name = "HipSTR2" %}
{% set version = "VERSION" %}
{% set vcommit = "VCOMMIT" %}
{% set sha = "SHA256" %}
{% set username = "USERNAME" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ username }}/{{ name }}/archive/{{ vcommit }}.tar.gz
  sha256: {{ sha }}
  patches:
    - patches/0001-use-version-from-config.patch
build:
  number: 0
  run_exports:
      - {{ pin_subpackage('hipstr2', max_pin="x.x") }}
  skip: true  # [win]
  script_env:
    - HIPSTR2_STATIC # default is to build dynamic, overridden in .github/workflows/bioconda.yml
  script:
    - mkdir -p "${PREFIX}/bin"
    - make version
    - STATIC="${HIPSTR2_STATIC:-0}" make HipSTR DenovoFinder
    - cp HipSTR DenovoFinder "${PREFIX}/bin/"

requirements:
  build:
    - make
    - {{ compiler('c') }} # for bundled cephes and htslib
    - {{ compiler('cxx') }}
  host:
    - xz
    - zlib
    - bzip2

test:
  commands:
    - HipSTR --help
    - DenovoFinder --help

about:
  home: https://github.com/{{ username }}/{{ name }}
  license: GPL-2
  license_file: LICENSE
  summary: Haplotype inference and phasing for Short Tandem Repeats
  description: Genotype and phase short tandem repeats using Illumina whole-genome sequencing data

extra:
  recipe-maintainers:
    - {{ username }}
  additional-platforms:
    - linux-aarch64
    - osx-arm64
